// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: mealplanner/v1/mealplanner.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MealPlannerService_SuggestRecipes_FullMethodName = "/mealplanner.v1.MealPlannerService/SuggestRecipes"
	MealPlannerService_GetWeekPlan_FullMethodName    = "/mealplanner.v1.MealPlannerService/GetWeekPlan"
	MealPlannerService_UpsertWeekPlan_FullMethodName = "/mealplanner.v1.MealPlannerService/UpsertWeekPlan"
)

// MealPlannerServiceClient is the client API for MealPlannerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service definition for meal planning
type MealPlannerServiceClient interface {
	// Suggests recipes based on given constraints
	SuggestRecipes(ctx context.Context, in *SuggestionsRequest, opts ...grpc.CallOption) (*SuggestionsResponse, error)
	// Retrieves a week plan for a given start date
	GetWeekPlan(ctx context.Context, in *GetWeekPlanRequest, opts ...grpc.CallOption) (*GetWeekPlanResponse, error)
	// Creates or updates a week plan
	UpsertWeekPlan(ctx context.Context, in *UpsertWeekPlanRequest, opts ...grpc.CallOption) (*UpsertWeekPlanResponse, error)
}

type mealPlannerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMealPlannerServiceClient(cc grpc.ClientConnInterface) MealPlannerServiceClient {
	return &mealPlannerServiceClient{cc}
}

func (c *mealPlannerServiceClient) SuggestRecipes(ctx context.Context, in *SuggestionsRequest, opts ...grpc.CallOption) (*SuggestionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuggestionsResponse)
	err := c.cc.Invoke(ctx, MealPlannerService_SuggestRecipes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mealPlannerServiceClient) GetWeekPlan(ctx context.Context, in *GetWeekPlanRequest, opts ...grpc.CallOption) (*GetWeekPlanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWeekPlanResponse)
	err := c.cc.Invoke(ctx, MealPlannerService_GetWeekPlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mealPlannerServiceClient) UpsertWeekPlan(ctx context.Context, in *UpsertWeekPlanRequest, opts ...grpc.CallOption) (*UpsertWeekPlanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertWeekPlanResponse)
	err := c.cc.Invoke(ctx, MealPlannerService_UpsertWeekPlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MealPlannerServiceServer is the server API for MealPlannerService service.
// All implementations must embed UnimplementedMealPlannerServiceServer
// for forward compatibility.
//
// Service definition for meal planning
type MealPlannerServiceServer interface {
	// Suggests recipes based on given constraints
	SuggestRecipes(context.Context, *SuggestionsRequest) (*SuggestionsResponse, error)
	// Retrieves a week plan for a given start date
	GetWeekPlan(context.Context, *GetWeekPlanRequest) (*GetWeekPlanResponse, error)
	// Creates or updates a week plan
	UpsertWeekPlan(context.Context, *UpsertWeekPlanRequest) (*UpsertWeekPlanResponse, error)
	mustEmbedUnimplementedMealPlannerServiceServer()
}

// UnimplementedMealPlannerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMealPlannerServiceServer struct{}

func (UnimplementedMealPlannerServiceServer) SuggestRecipes(context.Context, *SuggestionsRequest) (*SuggestionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SuggestRecipes not implemented")
}
func (UnimplementedMealPlannerServiceServer) GetWeekPlan(context.Context, *GetWeekPlanRequest) (*GetWeekPlanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWeekPlan not implemented")
}
func (UnimplementedMealPlannerServiceServer) UpsertWeekPlan(context.Context, *UpsertWeekPlanRequest) (*UpsertWeekPlanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpsertWeekPlan not implemented")
}
func (UnimplementedMealPlannerServiceServer) mustEmbedUnimplementedMealPlannerServiceServer() {}
func (UnimplementedMealPlannerServiceServer) testEmbeddedByValue()                            {}

// UnsafeMealPlannerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MealPlannerServiceServer will
// result in compilation errors.
type UnsafeMealPlannerServiceServer interface {
	mustEmbedUnimplementedMealPlannerServiceServer()
}

func RegisterMealPlannerServiceServer(s grpc.ServiceRegistrar, srv MealPlannerServiceServer) {
	// If the following call panics, it indicates UnimplementedMealPlannerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MealPlannerService_ServiceDesc, srv)
}

func _MealPlannerService_SuggestRecipes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SuggestionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MealPlannerServiceServer).SuggestRecipes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MealPlannerService_SuggestRecipes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MealPlannerServiceServer).SuggestRecipes(ctx, req.(*SuggestionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MealPlannerService_GetWeekPlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWeekPlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MealPlannerServiceServer).GetWeekPlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MealPlannerService_GetWeekPlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MealPlannerServiceServer).GetWeekPlan(ctx, req.(*GetWeekPlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MealPlannerService_UpsertWeekPlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertWeekPlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MealPlannerServiceServer).UpsertWeekPlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MealPlannerService_UpsertWeekPlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MealPlannerServiceServer).UpsertWeekPlan(ctx, req.(*UpsertWeekPlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MealPlannerService_ServiceDesc is the grpc.ServiceDesc for MealPlannerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MealPlannerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mealplanner.v1.MealPlannerService",
	HandlerType: (*MealPlannerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SuggestRecipes",
			Handler:    _MealPlannerService_SuggestRecipes_Handler,
		},
		{
			MethodName: "GetWeekPlan",
			Handler:    _MealPlannerService_GetWeekPlan_Handler,
		},
		{
			MethodName: "UpsertWeekPlan",
			Handler:    _MealPlannerService_UpsertWeekPlan_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mealplanner/v1/mealplanner.proto",
}
