FROM golang:1.22.7

RUN useradd -ms /bin/sh -u 1001 app
USER app

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY --chown=app:app *.go ./

# RUN go get -u github.com/swaggo/swag 

# RUN swag init

RUN CGO_ENABLED=0 GOOS=linux go build -o /PlatePilot

# Optional:
# To bind to a TCP port, runtime parameters must be supplied to the docker command.
# But we can document in the Dockerfile what ports
# the application is going to listen on by default.
# https://docs.docker.com/reference/dockerfile/#expose
EXPOSE 8080

CMD ["/PlatePilot"]