package main

import (
	// _ "PlatePilot/docs" // docs is generated by Swag CLI, you have to import it.

	handlers "PlatePilot/application/handlers"
	recipeRepository "PlatePilot/infrastructure/recipe"
	recipe_db "PlatePilot/infrastructure/recipe/db"

	"github.com/labstack/echo/v4"
)

// @title Recipe API
// @version 1.0
// @description This is a sample server for a recipe app.
// @host localhost:8080
// @BasePath /
func main() {
	e := echo.New()
	// TODO wait for fix?
	// e.GET("/swagger/*", echoSwagger.WrapHandler)

	// Load configuration
	dbConfig := recipe_db.NewDatabaseConfig()
	// Database connection
	db, err := recipe_db.NewPostgresDB(dbConfig)

	if err != nil {
		e.Logger.Fatal("Error during db init")
	}

	// Repositories
	recipeRepo := recipeRepository.NewPostgresRecipeRepository(db)

	handlers.RegisterRecipeHandlers(recipeRepo, e)

	e.Logger.Fatal(e.Start(":8080"))
}
