// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: recipe/v1/recipe.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RecipeService_GetRecipeById_FullMethodName          = "/recipe.v1.RecipeService/GetRecipeById"
	RecipeService_GetAllRecipes_FullMethodName          = "/recipe.v1.RecipeService/GetAllRecipes"
	RecipeService_CreateRecipe_FullMethodName           = "/recipe.v1.RecipeService/CreateRecipe"
	RecipeService_GetSimilarRecipes_FullMethodName      = "/recipe.v1.RecipeService/GetSimilarRecipes"
	RecipeService_GetRecipesByCuisine_FullMethodName    = "/recipe.v1.RecipeService/GetRecipesByCuisine"
	RecipeService_GetRecipesByIngredient_FullMethodName = "/recipe.v1.RecipeService/GetRecipesByIngredient"
	RecipeService_GetRecipesByAllergy_FullMethodName    = "/recipe.v1.RecipeService/GetRecipesByAllergy"
	RecipeService_GetUnits_FullMethodName               = "/recipe.v1.RecipeService/GetUnits"
	RecipeService_CreateUnit_FullMethodName             = "/recipe.v1.RecipeService/CreateUnit"
)

// RecipeServiceClient is the client API for RecipeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service definition for recipe management
type RecipeServiceClient interface {
	// Gets a recipe by its ID
	GetRecipeById(ctx context.Context, in *GetRecipeByIdRequest, opts ...grpc.CallOption) (*RecipeResponse, error)
	// Gets a paginated list of all recipes
	GetAllRecipes(ctx context.Context, in *GetAllRecipesRequest, opts ...grpc.CallOption) (*GetAllRecipesResponse, error)
	// Creates a new recipe
	CreateRecipe(ctx context.Context, in *CreateRecipeRequest, opts ...grpc.CallOption) (*RecipeResponse, error)
	// Gets recipes similar to a given recipe
	GetSimilarRecipes(ctx context.Context, in *GetSimilarRecipesRequest, opts ...grpc.CallOption) (*GetAllRecipesResponse, error)
	// Gets recipes by cuisine
	GetRecipesByCuisine(ctx context.Context, in *GetRecipesByCuisineRequest, opts ...grpc.CallOption) (*GetAllRecipesResponse, error)
	// Gets recipes by ingredient
	GetRecipesByIngredient(ctx context.Context, in *GetRecipesByIngredientRequest, opts ...grpc.CallOption) (*GetAllRecipesResponse, error)
	// Gets recipes avoiding an allergy
	GetRecipesByAllergy(ctx context.Context, in *GetRecipesByAllergyRequest, opts ...grpc.CallOption) (*GetAllRecipesResponse, error)
	// Gets available ingredient units
	GetUnits(ctx context.Context, in *GetUnitsRequest, opts ...grpc.CallOption) (*GetUnitsResponse, error)
	// Creates a new ingredient unit
	CreateUnit(ctx context.Context, in *CreateUnitRequest, opts ...grpc.CallOption) (*Unit, error)
}

type recipeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRecipeServiceClient(cc grpc.ClientConnInterface) RecipeServiceClient {
	return &recipeServiceClient{cc}
}

func (c *recipeServiceClient) GetRecipeById(ctx context.Context, in *GetRecipeByIdRequest, opts ...grpc.CallOption) (*RecipeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecipeResponse)
	err := c.cc.Invoke(ctx, RecipeService_GetRecipeById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recipeServiceClient) GetAllRecipes(ctx context.Context, in *GetAllRecipesRequest, opts ...grpc.CallOption) (*GetAllRecipesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllRecipesResponse)
	err := c.cc.Invoke(ctx, RecipeService_GetAllRecipes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recipeServiceClient) CreateRecipe(ctx context.Context, in *CreateRecipeRequest, opts ...grpc.CallOption) (*RecipeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecipeResponse)
	err := c.cc.Invoke(ctx, RecipeService_CreateRecipe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recipeServiceClient) GetSimilarRecipes(ctx context.Context, in *GetSimilarRecipesRequest, opts ...grpc.CallOption) (*GetAllRecipesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllRecipesResponse)
	err := c.cc.Invoke(ctx, RecipeService_GetSimilarRecipes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recipeServiceClient) GetRecipesByCuisine(ctx context.Context, in *GetRecipesByCuisineRequest, opts ...grpc.CallOption) (*GetAllRecipesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllRecipesResponse)
	err := c.cc.Invoke(ctx, RecipeService_GetRecipesByCuisine_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recipeServiceClient) GetRecipesByIngredient(ctx context.Context, in *GetRecipesByIngredientRequest, opts ...grpc.CallOption) (*GetAllRecipesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllRecipesResponse)
	err := c.cc.Invoke(ctx, RecipeService_GetRecipesByIngredient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recipeServiceClient) GetRecipesByAllergy(ctx context.Context, in *GetRecipesByAllergyRequest, opts ...grpc.CallOption) (*GetAllRecipesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllRecipesResponse)
	err := c.cc.Invoke(ctx, RecipeService_GetRecipesByAllergy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recipeServiceClient) GetUnits(ctx context.Context, in *GetUnitsRequest, opts ...grpc.CallOption) (*GetUnitsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUnitsResponse)
	err := c.cc.Invoke(ctx, RecipeService_GetUnits_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recipeServiceClient) CreateUnit(ctx context.Context, in *CreateUnitRequest, opts ...grpc.CallOption) (*Unit, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Unit)
	err := c.cc.Invoke(ctx, RecipeService_CreateUnit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RecipeServiceServer is the server API for RecipeService service.
// All implementations must embed UnimplementedRecipeServiceServer
// for forward compatibility.
//
// Service definition for recipe management
type RecipeServiceServer interface {
	// Gets a recipe by its ID
	GetRecipeById(context.Context, *GetRecipeByIdRequest) (*RecipeResponse, error)
	// Gets a paginated list of all recipes
	GetAllRecipes(context.Context, *GetAllRecipesRequest) (*GetAllRecipesResponse, error)
	// Creates a new recipe
	CreateRecipe(context.Context, *CreateRecipeRequest) (*RecipeResponse, error)
	// Gets recipes similar to a given recipe
	GetSimilarRecipes(context.Context, *GetSimilarRecipesRequest) (*GetAllRecipesResponse, error)
	// Gets recipes by cuisine
	GetRecipesByCuisine(context.Context, *GetRecipesByCuisineRequest) (*GetAllRecipesResponse, error)
	// Gets recipes by ingredient
	GetRecipesByIngredient(context.Context, *GetRecipesByIngredientRequest) (*GetAllRecipesResponse, error)
	// Gets recipes avoiding an allergy
	GetRecipesByAllergy(context.Context, *GetRecipesByAllergyRequest) (*GetAllRecipesResponse, error)
	// Gets available ingredient units
	GetUnits(context.Context, *GetUnitsRequest) (*GetUnitsResponse, error)
	// Creates a new ingredient unit
	CreateUnit(context.Context, *CreateUnitRequest) (*Unit, error)
	mustEmbedUnimplementedRecipeServiceServer()
}

// UnimplementedRecipeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRecipeServiceServer struct{}

func (UnimplementedRecipeServiceServer) GetRecipeById(context.Context, *GetRecipeByIdRequest) (*RecipeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRecipeById not implemented")
}
func (UnimplementedRecipeServiceServer) GetAllRecipes(context.Context, *GetAllRecipesRequest) (*GetAllRecipesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllRecipes not implemented")
}
func (UnimplementedRecipeServiceServer) CreateRecipe(context.Context, *CreateRecipeRequest) (*RecipeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateRecipe not implemented")
}
func (UnimplementedRecipeServiceServer) GetSimilarRecipes(context.Context, *GetSimilarRecipesRequest) (*GetAllRecipesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSimilarRecipes not implemented")
}
func (UnimplementedRecipeServiceServer) GetRecipesByCuisine(context.Context, *GetRecipesByCuisineRequest) (*GetAllRecipesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRecipesByCuisine not implemented")
}
func (UnimplementedRecipeServiceServer) GetRecipesByIngredient(context.Context, *GetRecipesByIngredientRequest) (*GetAllRecipesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRecipesByIngredient not implemented")
}
func (UnimplementedRecipeServiceServer) GetRecipesByAllergy(context.Context, *GetRecipesByAllergyRequest) (*GetAllRecipesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRecipesByAllergy not implemented")
}
func (UnimplementedRecipeServiceServer) GetUnits(context.Context, *GetUnitsRequest) (*GetUnitsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUnits not implemented")
}
func (UnimplementedRecipeServiceServer) CreateUnit(context.Context, *CreateUnitRequest) (*Unit, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateUnit not implemented")
}
func (UnimplementedRecipeServiceServer) mustEmbedUnimplementedRecipeServiceServer() {}
func (UnimplementedRecipeServiceServer) testEmbeddedByValue()                       {}

// UnsafeRecipeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RecipeServiceServer will
// result in compilation errors.
type UnsafeRecipeServiceServer interface {
	mustEmbedUnimplementedRecipeServiceServer()
}

func RegisterRecipeServiceServer(s grpc.ServiceRegistrar, srv RecipeServiceServer) {
	// If the following call panics, it indicates UnimplementedRecipeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RecipeService_ServiceDesc, srv)
}

func _RecipeService_GetRecipeById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRecipeByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecipeServiceServer).GetRecipeById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecipeService_GetRecipeById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecipeServiceServer).GetRecipeById(ctx, req.(*GetRecipeByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecipeService_GetAllRecipes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllRecipesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecipeServiceServer).GetAllRecipes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecipeService_GetAllRecipes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecipeServiceServer).GetAllRecipes(ctx, req.(*GetAllRecipesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecipeService_CreateRecipe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRecipeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecipeServiceServer).CreateRecipe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecipeService_CreateRecipe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecipeServiceServer).CreateRecipe(ctx, req.(*CreateRecipeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecipeService_GetSimilarRecipes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSimilarRecipesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecipeServiceServer).GetSimilarRecipes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecipeService_GetSimilarRecipes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecipeServiceServer).GetSimilarRecipes(ctx, req.(*GetSimilarRecipesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecipeService_GetRecipesByCuisine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRecipesByCuisineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecipeServiceServer).GetRecipesByCuisine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecipeService_GetRecipesByCuisine_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecipeServiceServer).GetRecipesByCuisine(ctx, req.(*GetRecipesByCuisineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecipeService_GetRecipesByIngredient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRecipesByIngredientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecipeServiceServer).GetRecipesByIngredient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecipeService_GetRecipesByIngredient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecipeServiceServer).GetRecipesByIngredient(ctx, req.(*GetRecipesByIngredientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecipeService_GetRecipesByAllergy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRecipesByAllergyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecipeServiceServer).GetRecipesByAllergy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecipeService_GetRecipesByAllergy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecipeServiceServer).GetRecipesByAllergy(ctx, req.(*GetRecipesByAllergyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecipeService_GetUnits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUnitsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecipeServiceServer).GetUnits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecipeService_GetUnits_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecipeServiceServer).GetUnits(ctx, req.(*GetUnitsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecipeService_CreateUnit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUnitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecipeServiceServer).CreateUnit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecipeService_CreateUnit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecipeServiceServer).CreateUnit(ctx, req.(*CreateUnitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RecipeService_ServiceDesc is the grpc.ServiceDesc for RecipeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RecipeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "recipe.v1.RecipeService",
	HandlerType: (*RecipeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRecipeById",
			Handler:    _RecipeService_GetRecipeById_Handler,
		},
		{
			MethodName: "GetAllRecipes",
			Handler:    _RecipeService_GetAllRecipes_Handler,
		},
		{
			MethodName: "CreateRecipe",
			Handler:    _RecipeService_CreateRecipe_Handler,
		},
		{
			MethodName: "GetSimilarRecipes",
			Handler:    _RecipeService_GetSimilarRecipes_Handler,
		},
		{
			MethodName: "GetRecipesByCuisine",
			Handler:    _RecipeService_GetRecipesByCuisine_Handler,
		},
		{
			MethodName: "GetRecipesByIngredient",
			Handler:    _RecipeService_GetRecipesByIngredient_Handler,
		},
		{
			MethodName: "GetRecipesByAllergy",
			Handler:    _RecipeService_GetRecipesByAllergy_Handler,
		},
		{
			MethodName: "GetUnits",
			Handler:    _RecipeService_GetUnits_Handler,
		},
		{
			MethodName: "CreateUnit",
			Handler:    _RecipeService_CreateUnit_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "recipe/v1/recipe.proto",
}
