// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// RecipeServiceClient is the client API for RecipeService service.
type RecipeServiceClient interface {
	GetRecipeById(ctx context.Context, in *GetRecipeByIdRequest, opts ...grpc.CallOption) (*RecipeResponse, error)
	GetAllRecipes(ctx context.Context, in *GetAllRecipesRequest, opts ...grpc.CallOption) (*GetAllRecipesResponse, error)
	CreateRecipe(ctx context.Context, in *CreateRecipeRequest, opts ...grpc.CallOption) (*RecipeResponse, error)
	GetSimilarRecipes(ctx context.Context, in *GetSimilarRecipesRequest, opts ...grpc.CallOption) (*GetAllRecipesResponse, error)
	GetRecipesByCuisine(ctx context.Context, in *GetRecipesByCuisineRequest, opts ...grpc.CallOption) (*GetAllRecipesResponse, error)
	GetRecipesByIngredient(ctx context.Context, in *GetRecipesByIngredientRequest, opts ...grpc.CallOption) (*GetAllRecipesResponse, error)
	GetRecipesByAllergy(ctx context.Context, in *GetRecipesByAllergyRequest, opts ...grpc.CallOption) (*GetAllRecipesResponse, error)
}

type recipeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRecipeServiceClient(cc grpc.ClientConnInterface) RecipeServiceClient {
	return &recipeServiceClient{cc}
}

func (c *recipeServiceClient) GetRecipeById(ctx context.Context, in *GetRecipeByIdRequest, opts ...grpc.CallOption) (*RecipeResponse, error) {
	out := new(RecipeResponse)
	err := c.cc.Invoke(ctx, "/recipe.v1.RecipeService/GetRecipeById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recipeServiceClient) GetAllRecipes(ctx context.Context, in *GetAllRecipesRequest, opts ...grpc.CallOption) (*GetAllRecipesResponse, error) {
	out := new(GetAllRecipesResponse)
	err := c.cc.Invoke(ctx, "/recipe.v1.RecipeService/GetAllRecipes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recipeServiceClient) CreateRecipe(ctx context.Context, in *CreateRecipeRequest, opts ...grpc.CallOption) (*RecipeResponse, error) {
	out := new(RecipeResponse)
	err := c.cc.Invoke(ctx, "/recipe.v1.RecipeService/CreateRecipe", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recipeServiceClient) GetSimilarRecipes(ctx context.Context, in *GetSimilarRecipesRequest, opts ...grpc.CallOption) (*GetAllRecipesResponse, error) {
	out := new(GetAllRecipesResponse)
	err := c.cc.Invoke(ctx, "/recipe.v1.RecipeService/GetSimilarRecipes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recipeServiceClient) GetRecipesByCuisine(ctx context.Context, in *GetRecipesByCuisineRequest, opts ...grpc.CallOption) (*GetAllRecipesResponse, error) {
	out := new(GetAllRecipesResponse)
	err := c.cc.Invoke(ctx, "/recipe.v1.RecipeService/GetRecipesByCuisine", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recipeServiceClient) GetRecipesByIngredient(ctx context.Context, in *GetRecipesByIngredientRequest, opts ...grpc.CallOption) (*GetAllRecipesResponse, error) {
	out := new(GetAllRecipesResponse)
	err := c.cc.Invoke(ctx, "/recipe.v1.RecipeService/GetRecipesByIngredient", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recipeServiceClient) GetRecipesByAllergy(ctx context.Context, in *GetRecipesByAllergyRequest, opts ...grpc.CallOption) (*GetAllRecipesResponse, error) {
	out := new(GetAllRecipesResponse)
	err := c.cc.Invoke(ctx, "/recipe.v1.RecipeService/GetRecipesByAllergy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RecipeServiceServer is the server API for RecipeService service.
type RecipeServiceServer interface {
	GetRecipeById(context.Context, *GetRecipeByIdRequest) (*RecipeResponse, error)
	GetAllRecipes(context.Context, *GetAllRecipesRequest) (*GetAllRecipesResponse, error)
	CreateRecipe(context.Context, *CreateRecipeRequest) (*RecipeResponse, error)
	GetSimilarRecipes(context.Context, *GetSimilarRecipesRequest) (*GetAllRecipesResponse, error)
	GetRecipesByCuisine(context.Context, *GetRecipesByCuisineRequest) (*GetAllRecipesResponse, error)
	GetRecipesByIngredient(context.Context, *GetRecipesByIngredientRequest) (*GetAllRecipesResponse, error)
	GetRecipesByAllergy(context.Context, *GetRecipesByAllergyRequest) (*GetAllRecipesResponse, error)
	mustEmbedUnimplementedRecipeServiceServer()
}

// UnimplementedRecipeServiceServer must be embedded to have forward compatible implementations.
type UnimplementedRecipeServiceServer struct {
}

func (UnimplementedRecipeServiceServer) GetRecipeById(context.Context, *GetRecipeByIdRequest) (*RecipeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRecipeById not implemented")
}

func (UnimplementedRecipeServiceServer) GetAllRecipes(context.Context, *GetAllRecipesRequest) (*GetAllRecipesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllRecipes not implemented")
}

func (UnimplementedRecipeServiceServer) CreateRecipe(context.Context, *CreateRecipeRequest) (*RecipeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRecipe not implemented")
}

func (UnimplementedRecipeServiceServer) GetSimilarRecipes(context.Context, *GetSimilarRecipesRequest) (*GetAllRecipesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSimilarRecipes not implemented")
}

func (UnimplementedRecipeServiceServer) GetRecipesByCuisine(context.Context, *GetRecipesByCuisineRequest) (*GetAllRecipesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRecipesByCuisine not implemented")
}

func (UnimplementedRecipeServiceServer) GetRecipesByIngredient(context.Context, *GetRecipesByIngredientRequest) (*GetAllRecipesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRecipesByIngredient not implemented")
}

func (UnimplementedRecipeServiceServer) GetRecipesByAllergy(context.Context, *GetRecipesByAllergyRequest) (*GetAllRecipesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRecipesByAllergy not implemented")
}

func (UnimplementedRecipeServiceServer) mustEmbedUnimplementedRecipeServiceServer() {}

// UnsafeRecipeServiceServer may be embedded to opt out of forward compatibility for this service.
type UnsafeRecipeServiceServer interface {
	mustEmbedUnimplementedRecipeServiceServer()
}

func RegisterRecipeServiceServer(s grpc.ServiceRegistrar, srv RecipeServiceServer) {
	s.RegisterService(&RecipeService_ServiceDesc, srv)
}

var RecipeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "recipe.v1.RecipeService",
	HandlerType: (*RecipeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRecipeById",
			Handler:    _RecipeService_GetRecipeById_Handler,
		},
		{
			MethodName: "GetAllRecipes",
			Handler:    _RecipeService_GetAllRecipes_Handler,
		},
		{
			MethodName: "CreateRecipe",
			Handler:    _RecipeService_CreateRecipe_Handler,
		},
		{
			MethodName: "GetSimilarRecipes",
			Handler:    _RecipeService_GetSimilarRecipes_Handler,
		},
		{
			MethodName: "GetRecipesByCuisine",
			Handler:    _RecipeService_GetRecipesByCuisine_Handler,
		},
		{
			MethodName: "GetRecipesByIngredient",
			Handler:    _RecipeService_GetRecipesByIngredient_Handler,
		},
		{
			MethodName: "GetRecipesByAllergy",
			Handler:    _RecipeService_GetRecipesByAllergy_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "recipe/v1/recipe.proto",
}

func _RecipeService_GetRecipeById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRecipeByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecipeServiceServer).GetRecipeById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/recipe.v1.RecipeService/GetRecipeById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecipeServiceServer).GetRecipeById(ctx, req.(*GetRecipeByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecipeService_GetAllRecipes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllRecipesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecipeServiceServer).GetAllRecipes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/recipe.v1.RecipeService/GetAllRecipes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecipeServiceServer).GetAllRecipes(ctx, req.(*GetAllRecipesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecipeService_CreateRecipe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRecipeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecipeServiceServer).CreateRecipe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/recipe.v1.RecipeService/CreateRecipe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecipeServiceServer).CreateRecipe(ctx, req.(*CreateRecipeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecipeService_GetSimilarRecipes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSimilarRecipesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecipeServiceServer).GetSimilarRecipes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/recipe.v1.RecipeService/GetSimilarRecipes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecipeServiceServer).GetSimilarRecipes(ctx, req.(*GetSimilarRecipesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecipeService_GetRecipesByCuisine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRecipesByCuisineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecipeServiceServer).GetRecipesByCuisine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/recipe.v1.RecipeService/GetRecipesByCuisine",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecipeServiceServer).GetRecipesByCuisine(ctx, req.(*GetRecipesByCuisineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecipeService_GetRecipesByIngredient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRecipesByIngredientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecipeServiceServer).GetRecipesByIngredient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/recipe.v1.RecipeService/GetRecipesByIngredient",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecipeServiceServer).GetRecipesByIngredient(ctx, req.(*GetRecipesByIngredientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecipeService_GetRecipesByAllergy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRecipesByAllergyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecipeServiceServer).GetRecipesByAllergy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/recipe.v1.RecipeService/GetRecipesByAllergy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecipeServiceServer).GetRecipesByAllergy(ctx, req.(*GetRecipesByAllergyRequest))
	}
	return interceptor(ctx, in, info, handler)
}
