// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: recipe/v1/recipe.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request for getting a recipe by ID
type GetRecipeByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecipeId      string                 `protobuf:"bytes,1,opt,name=recipe_id,json=recipeId,proto3" json:"recipe_id,omitempty"` // UUID string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecipeByIdRequest) Reset() {
	*x = GetRecipeByIdRequest{}
	mi := &file_recipe_v1_recipe_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecipeByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecipeByIdRequest) ProtoMessage() {}

func (x *GetRecipeByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recipe_v1_recipe_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecipeByIdRequest.ProtoReflect.Descriptor instead.
func (*GetRecipeByIdRequest) Descriptor() ([]byte, []int) {
	return file_recipe_v1_recipe_proto_rawDescGZIP(), []int{0}
}

func (x *GetRecipeByIdRequest) GetRecipeId() string {
	if x != nil {
		return x.RecipeId
	}
	return ""
}

// Request for getting all recipes with pagination
type GetAllRecipesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageIndex     int32                  `protobuf:"varint,1,opt,name=page_index,json=pageIndex,proto3" json:"page_index,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllRecipesRequest) Reset() {
	*x = GetAllRecipesRequest{}
	mi := &file_recipe_v1_recipe_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllRecipesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllRecipesRequest) ProtoMessage() {}

func (x *GetAllRecipesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recipe_v1_recipe_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllRecipesRequest.ProtoReflect.Descriptor instead.
func (*GetAllRecipesRequest) Descriptor() ([]byte, []int) {
	return file_recipe_v1_recipe_proto_rawDescGZIP(), []int{1}
}

func (x *GetAllRecipesRequest) GetPageIndex() int32 {
	if x != nil {
		return x.PageIndex
	}
	return 0
}

func (x *GetAllRecipesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// Response containing multiple recipes
type GetAllRecipesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Recipes       []*RecipeResponse      `protobuf:"bytes,1,rep,name=recipes,proto3" json:"recipes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllRecipesResponse) Reset() {
	*x = GetAllRecipesResponse{}
	mi := &file_recipe_v1_recipe_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllRecipesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllRecipesResponse) ProtoMessage() {}

func (x *GetAllRecipesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recipe_v1_recipe_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllRecipesResponse.ProtoReflect.Descriptor instead.
func (*GetAllRecipesResponse) Descriptor() ([]byte, []int) {
	return file_recipe_v1_recipe_proto_rawDescGZIP(), []int{2}
}

func (x *GetAllRecipesResponse) GetRecipes() []*RecipeResponse {
	if x != nil {
		return x.Recipes
	}
	return nil
}

// Request for creating a new recipe
type CreateRecipeRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description      string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	PrepTime         string                 `protobuf:"bytes,3,opt,name=prep_time,json=prepTime,proto3" json:"prep_time,omitempty"`
	CookTime         string                 `protobuf:"bytes,4,opt,name=cook_time,json=cookTime,proto3" json:"cook_time,omitempty"`
	MainIngredientId string                 `protobuf:"bytes,5,opt,name=main_ingredient_id,json=mainIngredientId,proto3" json:"main_ingredient_id,omitempty"` // UUID string
	CuisineId        string                 `protobuf:"bytes,6,opt,name=cuisine_id,json=cuisineId,proto3" json:"cuisine_id,omitempty"`                        // UUID string
	IngredientIds    []string               `protobuf:"bytes,7,rep,name=ingredient_ids,json=ingredientIds,proto3" json:"ingredient_ids,omitempty"`            // UUID strings
	Directions       []string               `protobuf:"bytes,8,rep,name=directions,proto3" json:"directions,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateRecipeRequest) Reset() {
	*x = CreateRecipeRequest{}
	mi := &file_recipe_v1_recipe_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRecipeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRecipeRequest) ProtoMessage() {}

func (x *CreateRecipeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recipe_v1_recipe_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRecipeRequest.ProtoReflect.Descriptor instead.
func (*CreateRecipeRequest) Descriptor() ([]byte, []int) {
	return file_recipe_v1_recipe_proto_rawDescGZIP(), []int{3}
}

func (x *CreateRecipeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRecipeRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateRecipeRequest) GetPrepTime() string {
	if x != nil {
		return x.PrepTime
	}
	return ""
}

func (x *CreateRecipeRequest) GetCookTime() string {
	if x != nil {
		return x.CookTime
	}
	return ""
}

func (x *CreateRecipeRequest) GetMainIngredientId() string {
	if x != nil {
		return x.MainIngredientId
	}
	return ""
}

func (x *CreateRecipeRequest) GetCuisineId() string {
	if x != nil {
		return x.CuisineId
	}
	return ""
}

func (x *CreateRecipeRequest) GetIngredientIds() []string {
	if x != nil {
		return x.IngredientIds
	}
	return nil
}

func (x *CreateRecipeRequest) GetDirections() []string {
	if x != nil {
		return x.Directions
	}
	return nil
}

// Request for getting similar recipes
type GetSimilarRecipesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecipeId      string                 `protobuf:"bytes,1,opt,name=recipe_id,json=recipeId,proto3" json:"recipe_id,omitempty"` // UUID string
	Amount        int32                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSimilarRecipesRequest) Reset() {
	*x = GetSimilarRecipesRequest{}
	mi := &file_recipe_v1_recipe_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSimilarRecipesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSimilarRecipesRequest) ProtoMessage() {}

func (x *GetSimilarRecipesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recipe_v1_recipe_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSimilarRecipesRequest.ProtoReflect.Descriptor instead.
func (*GetSimilarRecipesRequest) Descriptor() ([]byte, []int) {
	return file_recipe_v1_recipe_proto_rawDescGZIP(), []int{4}
}

func (x *GetSimilarRecipesRequest) GetRecipeId() string {
	if x != nil {
		return x.RecipeId
	}
	return ""
}

func (x *GetSimilarRecipesRequest) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

// Request for getting recipes by cuisine
type GetRecipesByCuisineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CuisineId     string                 `protobuf:"bytes,1,opt,name=cuisine_id,json=cuisineId,proto3" json:"cuisine_id,omitempty"` // UUID string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecipesByCuisineRequest) Reset() {
	*x = GetRecipesByCuisineRequest{}
	mi := &file_recipe_v1_recipe_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecipesByCuisineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecipesByCuisineRequest) ProtoMessage() {}

func (x *GetRecipesByCuisineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recipe_v1_recipe_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecipesByCuisineRequest.ProtoReflect.Descriptor instead.
func (*GetRecipesByCuisineRequest) Descriptor() ([]byte, []int) {
	return file_recipe_v1_recipe_proto_rawDescGZIP(), []int{5}
}

func (x *GetRecipesByCuisineRequest) GetCuisineId() string {
	if x != nil {
		return x.CuisineId
	}
	return ""
}

// Request for getting recipes by ingredient
type GetRecipesByIngredientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IngredientId  string                 `protobuf:"bytes,1,opt,name=ingredient_id,json=ingredientId,proto3" json:"ingredient_id,omitempty"` // UUID string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecipesByIngredientRequest) Reset() {
	*x = GetRecipesByIngredientRequest{}
	mi := &file_recipe_v1_recipe_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecipesByIngredientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecipesByIngredientRequest) ProtoMessage() {}

func (x *GetRecipesByIngredientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recipe_v1_recipe_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecipesByIngredientRequest.ProtoReflect.Descriptor instead.
func (*GetRecipesByIngredientRequest) Descriptor() ([]byte, []int) {
	return file_recipe_v1_recipe_proto_rawDescGZIP(), []int{6}
}

func (x *GetRecipesByIngredientRequest) GetIngredientId() string {
	if x != nil {
		return x.IngredientId
	}
	return ""
}

// Request for getting recipes avoiding an allergy
type GetRecipesByAllergyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AllergyId     string                 `protobuf:"bytes,1,opt,name=allergy_id,json=allergyId,proto3" json:"allergy_id,omitempty"` // UUID string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecipesByAllergyRequest) Reset() {
	*x = GetRecipesByAllergyRequest{}
	mi := &file_recipe_v1_recipe_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecipesByAllergyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecipesByAllergyRequest) ProtoMessage() {}

func (x *GetRecipesByAllergyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recipe_v1_recipe_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecipesByAllergyRequest.ProtoReflect.Descriptor instead.
func (*GetRecipesByAllergyRequest) Descriptor() ([]byte, []int) {
	return file_recipe_v1_recipe_proto_rawDescGZIP(), []int{7}
}

func (x *GetRecipesByAllergyRequest) GetAllergyId() string {
	if x != nil {
		return x.AllergyId
	}
	return ""
}

// Response containing recipe details
type RecipeResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // UUID string
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description    string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	PrepTime       string                 `protobuf:"bytes,4,opt,name=prep_time,json=prepTime,proto3" json:"prep_time,omitempty"`
	CookTime       string                 `protobuf:"bytes,5,opt,name=cook_time,json=cookTime,proto3" json:"cook_time,omitempty"`
	MainIngredient *Ingredient            `protobuf:"bytes,6,opt,name=main_ingredient,json=mainIngredient,proto3" json:"main_ingredient,omitempty"`
	Cuisine        *Cuisine               `protobuf:"bytes,7,opt,name=cuisine,proto3" json:"cuisine,omitempty"`
	Ingredients    []*Ingredient          `protobuf:"bytes,8,rep,name=ingredients,proto3" json:"ingredients,omitempty"`
	Directions     []string               `protobuf:"bytes,9,rep,name=directions,proto3" json:"directions,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RecipeResponse) Reset() {
	*x = RecipeResponse{}
	mi := &file_recipe_v1_recipe_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecipeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecipeResponse) ProtoMessage() {}

func (x *RecipeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recipe_v1_recipe_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecipeResponse.ProtoReflect.Descriptor instead.
func (*RecipeResponse) Descriptor() ([]byte, []int) {
	return file_recipe_v1_recipe_proto_rawDescGZIP(), []int{8}
}

func (x *RecipeResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RecipeResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RecipeResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RecipeResponse) GetPrepTime() string {
	if x != nil {
		return x.PrepTime
	}
	return ""
}

func (x *RecipeResponse) GetCookTime() string {
	if x != nil {
		return x.CookTime
	}
	return ""
}

func (x *RecipeResponse) GetMainIngredient() *Ingredient {
	if x != nil {
		return x.MainIngredient
	}
	return nil
}

func (x *RecipeResponse) GetCuisine() *Cuisine {
	if x != nil {
		return x.Cuisine
	}
	return nil
}

func (x *RecipeResponse) GetIngredients() []*Ingredient {
	if x != nil {
		return x.Ingredients
	}
	return nil
}

func (x *RecipeResponse) GetDirections() []string {
	if x != nil {
		return x.Directions
	}
	return nil
}

// Ingredient entity
type Ingredient struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // UUID string
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ingredient) Reset() {
	*x = Ingredient{}
	mi := &file_recipe_v1_recipe_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ingredient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ingredient) ProtoMessage() {}

func (x *Ingredient) ProtoReflect() protoreflect.Message {
	mi := &file_recipe_v1_recipe_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ingredient.ProtoReflect.Descriptor instead.
func (*Ingredient) Descriptor() ([]byte, []int) {
	return file_recipe_v1_recipe_proto_rawDescGZIP(), []int{9}
}

func (x *Ingredient) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Ingredient) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Cuisine entity
type Cuisine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // UUID string
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cuisine) Reset() {
	*x = Cuisine{}
	mi := &file_recipe_v1_recipe_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cuisine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cuisine) ProtoMessage() {}

func (x *Cuisine) ProtoReflect() protoreflect.Message {
	mi := &file_recipe_v1_recipe_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cuisine.ProtoReflect.Descriptor instead.
func (*Cuisine) Descriptor() ([]byte, []int) {
	return file_recipe_v1_recipe_proto_rawDescGZIP(), []int{10}
}

func (x *Cuisine) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Cuisine) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_recipe_v1_recipe_proto protoreflect.FileDescriptor

const file_recipe_v1_recipe_proto_rawDesc = "" +
	"\n" +
	"\x16recipe/v1/recipe.proto\x12\trecipe.v1\"3\n" +
	"\x14GetRecipeByIdRequest\x12\x1b\n" +
	"\trecipe_id\x18\x01 \x01(\tR\brecipeId\"R\n" +
	"\x14GetAllRecipesRequest\x12\x1d\n" +
	"\n" +
	"page_index\x18\x01 \x01(\x05R\tpageIndex\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"L\n" +
	"\x15GetAllRecipesResponse\x123\n" +
	"\arecipes\x18\x01 \x03(\v2\x19.recipe.v1.RecipeResponseR\arecipes\"\x99\x02\n" +
	"\x13CreateRecipeRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1b\n" +
	"\tprep_time\x18\x03 \x01(\tR\bprepTime\x12\x1b\n" +
	"\tcook_time\x18\x04 \x01(\tR\bcookTime\x12,\n" +
	"\x12main_ingredient_id\x18\x05 \x01(\tR\x10mainIngredientId\x12\x1d\n" +
	"\n" +
	"cuisine_id\x18\x06 \x01(\tR\tcuisineId\x12%\n" +
	"\x0eingredient_ids\x18\a \x03(\tR\ringredientIds\x12\x1e\n" +
	"\n" +
	"directions\x18\b \x03(\tR\n" +
	"directions\"O\n" +
	"\x18GetSimilarRecipesRequest\x12\x1b\n" +
	"\trecipe_id\x18\x01 \x01(\tR\brecipeId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x05R\x06amount\";\n" +
	"\x1aGetRecipesByCuisineRequest\x12\x1d\n" +
	"\n" +
	"cuisine_id\x18\x01 \x01(\tR\tcuisineId\"D\n" +
	"\x1dGetRecipesByIngredientRequest\x12#\n" +
	"\ringredient_id\x18\x01 \x01(\tR\fingredientId\";\n" +
	"\x1aGetRecipesByAllergyRequest\x12\x1d\n" +
	"\n" +
	"allergy_id\x18\x01 \x01(\tR\tallergyId\"\xd7\x02\n" +
	"\x0eRecipeResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1b\n" +
	"\tprep_time\x18\x04 \x01(\tR\bprepTime\x12\x1b\n" +
	"\tcook_time\x18\x05 \x01(\tR\bcookTime\x12>\n" +
	"\x0fmain_ingredient\x18\x06 \x01(\v2\x15.recipe.v1.IngredientR\x0emainIngredient\x12,\n" +
	"\acuisine\x18\a \x01(\v2\x12.recipe.v1.CuisineR\acuisine\x127\n" +
	"\vingredients\x18\b \x03(\v2\x15.recipe.v1.IngredientR\vingredients\x12\x1e\n" +
	"\n" +
	"directions\x18\t \x03(\tR\n" +
	"directions\"0\n" +
	"\n" +
	"Ingredient\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"-\n" +
	"\aCuisine\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name2\xfd\x04\n" +
	"\rRecipeService\x12K\n" +
	"\rGetRecipeById\x12\x1f.recipe.v1.GetRecipeByIdRequest\x1a\x19.recipe.v1.RecipeResponse\x12R\n" +
	"\rGetAllRecipes\x12\x1f.recipe.v1.GetAllRecipesRequest\x1a .recipe.v1.GetAllRecipesResponse\x12I\n" +
	"\fCreateRecipe\x12\x1e.recipe.v1.CreateRecipeRequest\x1a\x19.recipe.v1.RecipeResponse\x12Z\n" +
	"\x11GetSimilarRecipes\x12#.recipe.v1.GetSimilarRecipesRequest\x1a .recipe.v1.GetAllRecipesResponse\x12^\n" +
	"\x13GetRecipesByCuisine\x12%.recipe.v1.GetRecipesByCuisineRequest\x1a .recipe.v1.GetAllRecipesResponse\x12d\n" +
	"\x16GetRecipesByIngredient\x12(.recipe.v1.GetRecipesByIngredientRequest\x1a .recipe.v1.GetAllRecipesResponse\x12^\n" +
	"\x13GetRecipesByAllergy\x12%.recipe.v1.GetRecipesByAllergyRequest\x1a .recipe.v1.GetAllRecipesResponseB2Z0github.com/platepilot/backend/internal/recipe/pbb\x06proto3"

var (
	file_recipe_v1_recipe_proto_rawDescOnce sync.Once
	file_recipe_v1_recipe_proto_rawDescData []byte
)

func file_recipe_v1_recipe_proto_rawDescGZIP() []byte {
	file_recipe_v1_recipe_proto_rawDescOnce.Do(func() {
		file_recipe_v1_recipe_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_recipe_v1_recipe_proto_rawDesc), len(file_recipe_v1_recipe_proto_rawDesc)))
	})
	return file_recipe_v1_recipe_proto_rawDescData
}

var file_recipe_v1_recipe_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_recipe_v1_recipe_proto_goTypes = []any{
	(*GetRecipeByIdRequest)(nil),          // 0: recipe.v1.GetRecipeByIdRequest
	(*GetAllRecipesRequest)(nil),          // 1: recipe.v1.GetAllRecipesRequest
	(*GetAllRecipesResponse)(nil),         // 2: recipe.v1.GetAllRecipesResponse
	(*CreateRecipeRequest)(nil),           // 3: recipe.v1.CreateRecipeRequest
	(*GetSimilarRecipesRequest)(nil),      // 4: recipe.v1.GetSimilarRecipesRequest
	(*GetRecipesByCuisineRequest)(nil),    // 5: recipe.v1.GetRecipesByCuisineRequest
	(*GetRecipesByIngredientRequest)(nil), // 6: recipe.v1.GetRecipesByIngredientRequest
	(*GetRecipesByAllergyRequest)(nil),    // 7: recipe.v1.GetRecipesByAllergyRequest
	(*RecipeResponse)(nil),                // 8: recipe.v1.RecipeResponse
	(*Ingredient)(nil),                    // 9: recipe.v1.Ingredient
	(*Cuisine)(nil),                       // 10: recipe.v1.Cuisine
}
var file_recipe_v1_recipe_proto_depIdxs = []int32{
	8,  // 0: recipe.v1.GetAllRecipesResponse.recipes:type_name -> recipe.v1.RecipeResponse
	9,  // 1: recipe.v1.RecipeResponse.main_ingredient:type_name -> recipe.v1.Ingredient
	10, // 2: recipe.v1.RecipeResponse.cuisine:type_name -> recipe.v1.Cuisine
	9,  // 3: recipe.v1.RecipeResponse.ingredients:type_name -> recipe.v1.Ingredient
	0,  // 4: recipe.v1.RecipeService.GetRecipeById:input_type -> recipe.v1.GetRecipeByIdRequest
	1,  // 5: recipe.v1.RecipeService.GetAllRecipes:input_type -> recipe.v1.GetAllRecipesRequest
	3,  // 6: recipe.v1.RecipeService.CreateRecipe:input_type -> recipe.v1.CreateRecipeRequest
	4,  // 7: recipe.v1.RecipeService.GetSimilarRecipes:input_type -> recipe.v1.GetSimilarRecipesRequest
	5,  // 8: recipe.v1.RecipeService.GetRecipesByCuisine:input_type -> recipe.v1.GetRecipesByCuisineRequest
	6,  // 9: recipe.v1.RecipeService.GetRecipesByIngredient:input_type -> recipe.v1.GetRecipesByIngredientRequest
	7,  // 10: recipe.v1.RecipeService.GetRecipesByAllergy:input_type -> recipe.v1.GetRecipesByAllergyRequest
	8,  // 11: recipe.v1.RecipeService.GetRecipeById:output_type -> recipe.v1.RecipeResponse
	2,  // 12: recipe.v1.RecipeService.GetAllRecipes:output_type -> recipe.v1.GetAllRecipesResponse
	8,  // 13: recipe.v1.RecipeService.CreateRecipe:output_type -> recipe.v1.RecipeResponse
	2,  // 14: recipe.v1.RecipeService.GetSimilarRecipes:output_type -> recipe.v1.GetAllRecipesResponse
	2,  // 15: recipe.v1.RecipeService.GetRecipesByCuisine:output_type -> recipe.v1.GetAllRecipesResponse
	2,  // 16: recipe.v1.RecipeService.GetRecipesByIngredient:output_type -> recipe.v1.GetAllRecipesResponse
	2,  // 17: recipe.v1.RecipeService.GetRecipesByAllergy:output_type -> recipe.v1.GetAllRecipesResponse
	11, // [11:18] is the sub-list for method output_type
	4,  // [4:11] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_recipe_v1_recipe_proto_init() }
func file_recipe_v1_recipe_proto_init() {
	if File_recipe_v1_recipe_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_recipe_v1_recipe_proto_rawDesc), len(file_recipe_v1_recipe_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_recipe_v1_recipe_proto_goTypes,
		DependencyIndexes: file_recipe_v1_recipe_proto_depIdxs,
		MessageInfos:      file_recipe_v1_recipe_proto_msgTypes,
	}.Build()
	File_recipe_v1_recipe_proto = out.File
	file_recipe_v1_recipe_proto_goTypes = nil
	file_recipe_v1_recipe_proto_depIdxs = nil
}
