// Code generated by protoc-gen-go. DO NOT EDIT.
// source: recipe/v1/recipe.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request for getting a recipe by ID
type GetRecipeByIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RecipeId string `protobuf:"bytes,1,opt,name=recipe_id,json=recipeId,proto3" json:"recipe_id,omitempty"`
}

func (x *GetRecipeByIdRequest) Reset() {
	*x = GetRecipeByIdRequest{}
}

func (x *GetRecipeByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecipeByIdRequest) ProtoMessage() {}

func (x *GetRecipeByIdRequest) ProtoReflect() protoreflect.Message {
	return nil
}

func (x *GetRecipeByIdRequest) GetRecipeId() string {
	if x != nil {
		return x.RecipeId
	}
	return ""
}

// Request for getting all recipes with pagination
type GetAllRecipesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PageIndex int32 `protobuf:"varint,1,opt,name=page_index,json=pageIndex,proto3" json:"page_index,omitempty"`
	PageSize  int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
}

func (x *GetAllRecipesRequest) Reset() {
	*x = GetAllRecipesRequest{}
}

func (x *GetAllRecipesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllRecipesRequest) ProtoMessage() {}

func (x *GetAllRecipesRequest) ProtoReflect() protoreflect.Message {
	return nil
}

func (x *GetAllRecipesRequest) GetPageIndex() int32 {
	if x != nil {
		return x.PageIndex
	}
	return 0
}

func (x *GetAllRecipesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// Response containing multiple recipes
type GetAllRecipesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Recipes []*RecipeResponse `protobuf:"bytes,1,rep,name=recipes,proto3" json:"recipes,omitempty"`
}

func (x *GetAllRecipesResponse) Reset() {
	*x = GetAllRecipesResponse{}
}

func (x *GetAllRecipesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllRecipesResponse) ProtoMessage() {}

func (x *GetAllRecipesResponse) ProtoReflect() protoreflect.Message {
	return nil
}

func (x *GetAllRecipesResponse) GetRecipes() []*RecipeResponse {
	if x != nil {
		return x.Recipes
	}
	return nil
}

// Request for creating a new recipe
type CreateRecipeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name             string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description      string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	PrepTime         string   `protobuf:"bytes,3,opt,name=prep_time,json=prepTime,proto3" json:"prep_time,omitempty"`
	CookTime         string   `protobuf:"bytes,4,opt,name=cook_time,json=cookTime,proto3" json:"cook_time,omitempty"`
	MainIngredientId string   `protobuf:"bytes,5,opt,name=main_ingredient_id,json=mainIngredientId,proto3" json:"main_ingredient_id,omitempty"`
	CuisineId        string   `protobuf:"bytes,6,opt,name=cuisine_id,json=cuisineId,proto3" json:"cuisine_id,omitempty"`
	IngredientIds    []string `protobuf:"bytes,7,rep,name=ingredient_ids,json=ingredientIds,proto3" json:"ingredient_ids,omitempty"`
	Directions       []string `protobuf:"bytes,8,rep,name=directions,proto3" json:"directions,omitempty"`
}

func (x *CreateRecipeRequest) Reset() {
	*x = CreateRecipeRequest{}
}

func (x *CreateRecipeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRecipeRequest) ProtoMessage() {}

func (x *CreateRecipeRequest) ProtoReflect() protoreflect.Message {
	return nil
}

func (x *CreateRecipeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRecipeRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateRecipeRequest) GetPrepTime() string {
	if x != nil {
		return x.PrepTime
	}
	return ""
}

func (x *CreateRecipeRequest) GetCookTime() string {
	if x != nil {
		return x.CookTime
	}
	return ""
}

func (x *CreateRecipeRequest) GetMainIngredientId() string {
	if x != nil {
		return x.MainIngredientId
	}
	return ""
}

func (x *CreateRecipeRequest) GetCuisineId() string {
	if x != nil {
		return x.CuisineId
	}
	return ""
}

func (x *CreateRecipeRequest) GetIngredientIds() []string {
	if x != nil {
		return x.IngredientIds
	}
	return nil
}

func (x *CreateRecipeRequest) GetDirections() []string {
	if x != nil {
		return x.Directions
	}
	return nil
}

// Request for getting similar recipes
type GetSimilarRecipesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RecipeId string `protobuf:"bytes,1,opt,name=recipe_id,json=recipeId,proto3" json:"recipe_id,omitempty"`
	Amount   int32  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *GetSimilarRecipesRequest) Reset() {
	*x = GetSimilarRecipesRequest{}
}

func (x *GetSimilarRecipesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSimilarRecipesRequest) ProtoMessage() {}

func (x *GetSimilarRecipesRequest) ProtoReflect() protoreflect.Message {
	return nil
}

func (x *GetSimilarRecipesRequest) GetRecipeId() string {
	if x != nil {
		return x.RecipeId
	}
	return ""
}

func (x *GetSimilarRecipesRequest) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

// Request for getting recipes by cuisine
type GetRecipesByCuisineRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CuisineId string `protobuf:"bytes,1,opt,name=cuisine_id,json=cuisineId,proto3" json:"cuisine_id,omitempty"`
}

func (x *GetRecipesByCuisineRequest) Reset() {
	*x = GetRecipesByCuisineRequest{}
}

func (x *GetRecipesByCuisineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecipesByCuisineRequest) ProtoMessage() {}

func (x *GetRecipesByCuisineRequest) ProtoReflect() protoreflect.Message {
	return nil
}

func (x *GetRecipesByCuisineRequest) GetCuisineId() string {
	if x != nil {
		return x.CuisineId
	}
	return ""
}

// Request for getting recipes by ingredient
type GetRecipesByIngredientRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IngredientId string `protobuf:"bytes,1,opt,name=ingredient_id,json=ingredientId,proto3" json:"ingredient_id,omitempty"`
}

func (x *GetRecipesByIngredientRequest) Reset() {
	*x = GetRecipesByIngredientRequest{}
}

func (x *GetRecipesByIngredientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecipesByIngredientRequest) ProtoMessage() {}

func (x *GetRecipesByIngredientRequest) ProtoReflect() protoreflect.Message {
	return nil
}

func (x *GetRecipesByIngredientRequest) GetIngredientId() string {
	if x != nil {
		return x.IngredientId
	}
	return ""
}

// Request for getting recipes avoiding an allergy
type GetRecipesByAllergyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AllergyId string `protobuf:"bytes,1,opt,name=allergy_id,json=allergyId,proto3" json:"allergy_id,omitempty"`
}

func (x *GetRecipesByAllergyRequest) Reset() {
	*x = GetRecipesByAllergyRequest{}
}

func (x *GetRecipesByAllergyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecipesByAllergyRequest) ProtoMessage() {}

func (x *GetRecipesByAllergyRequest) ProtoReflect() protoreflect.Message {
	return nil
}

func (x *GetRecipesByAllergyRequest) GetAllergyId() string {
	if x != nil {
		return x.AllergyId
	}
	return ""
}

// Response containing recipe details
type RecipeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             string        `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string        `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description    string        `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	PrepTime       string        `protobuf:"bytes,4,opt,name=prep_time,json=prepTime,proto3" json:"prep_time,omitempty"`
	CookTime       string        `protobuf:"bytes,5,opt,name=cook_time,json=cookTime,proto3" json:"cook_time,omitempty"`
	MainIngredient *Ingredient   `protobuf:"bytes,6,opt,name=main_ingredient,json=mainIngredient,proto3" json:"main_ingredient,omitempty"`
	Cuisine        *Cuisine      `protobuf:"bytes,7,opt,name=cuisine,proto3" json:"cuisine,omitempty"`
	Ingredients    []*Ingredient `protobuf:"bytes,8,rep,name=ingredients,proto3" json:"ingredients,omitempty"`
	Directions     []string      `protobuf:"bytes,9,rep,name=directions,proto3" json:"directions,omitempty"`
}

func (x *RecipeResponse) Reset() {
	*x = RecipeResponse{}
}

func (x *RecipeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecipeResponse) ProtoMessage() {}

func (x *RecipeResponse) ProtoReflect() protoreflect.Message {
	return nil
}

func (x *RecipeResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RecipeResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RecipeResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RecipeResponse) GetPrepTime() string {
	if x != nil {
		return x.PrepTime
	}
	return ""
}

func (x *RecipeResponse) GetCookTime() string {
	if x != nil {
		return x.CookTime
	}
	return ""
}

func (x *RecipeResponse) GetMainIngredient() *Ingredient {
	if x != nil {
		return x.MainIngredient
	}
	return nil
}

func (x *RecipeResponse) GetCuisine() *Cuisine {
	if x != nil {
		return x.Cuisine
	}
	return nil
}

func (x *RecipeResponse) GetIngredients() []*Ingredient {
	if x != nil {
		return x.Ingredients
	}
	return nil
}

func (x *RecipeResponse) GetDirections() []string {
	if x != nil {
		return x.Directions
	}
	return nil
}

// Ingredient entity
type Ingredient struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Ingredient) Reset() {
	*x = Ingredient{}
}

func (x *Ingredient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ingredient) ProtoMessage() {}

func (x *Ingredient) ProtoReflect() protoreflect.Message {
	return nil
}

func (x *Ingredient) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Ingredient) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Cuisine entity
type Cuisine struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Cuisine) Reset() {
	*x = Cuisine{}
}

func (x *Cuisine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cuisine) ProtoMessage() {}

func (x *Cuisine) ProtoReflect() protoreflect.Message {
	return nil
}

func (x *Cuisine) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Cuisine) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_recipe_v1_recipe_proto protoreflect.FileDescriptor

var _ protoreflect.FileDescriptor = File_recipe_v1_recipe_proto

func init() {
}

var _ sync.Locker
var _ reflect.Kind
