name: PlatePilot
options:
  bundleIdPrefix: com.platepilot
  deploymentTarget:
    iOS: "26.0"
settings:
  base:
    SWIFT_VERSION: 6.0
    IPHONEOS_DEPLOYMENT_TARGET: "26.0"

configs:
  Debug: debug
  Release: release

targets:
  PlatePilot:
    type: application
    platform: iOS
    deploymentTarget: "26.0"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.platepilot.app
        GENERATE_INFOPLIST_FILE: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        INFOPLIST_KEY_NSAppTransportSecurity_NSAllowsArbitraryLoads: YES
        INFOPLIST_KEY_UILaunchStoryboardName: LaunchScreen
        INFOPLIST_KEY_UIRequiresFullScreen: YES
        INFOPLIST_KEY_UIUserInterfaceStyle: Light
        INFOPLIST_KEY_UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        INFOPLIST_KEY_UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
    sources:
      - path: .
        excludes:
          - project.yml
          - "**/*.md"
          - Resources
    resources:
      - path: Resources
