// <auto-generated/>
#pragma warning disable CS0618
using Infrastructure.RecipeApi.Client.Api.Recipes.All;
using Infrastructure.RecipeApi.Client.Api.Recipes.Create;
using Infrastructure.RecipeApi.Client.Api.Recipes.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Infrastructure.RecipeApi.Client.Api.Recipes
{
    /// <summary>
    /// Builds and executes requests for operations under \api\recipes
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class RecipesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The all property</summary>
        public global::Infrastructure.RecipeApi.Client.Api.Recipes.All.AllRequestBuilder All
        {
            get => new global::Infrastructure.RecipeApi.Client.Api.Recipes.All.AllRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The create property</summary>
        public global::Infrastructure.RecipeApi.Client.Api.Recipes.Create.CreateRequestBuilder Create
        {
            get => new global::Infrastructure.RecipeApi.Client.Api.Recipes.Create.CreateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Infrastructure.RecipeApi.Client.api.recipes.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Infrastructure.RecipeApi.Client.Api.Recipes.Item.RecipesItemRequestBuilder"/></returns>
        public global::Infrastructure.RecipeApi.Client.Api.Recipes.Item.RecipesItemRequestBuilder this[Guid position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id", position);
                return new global::Infrastructure.RecipeApi.Client.Api.Recipes.Item.RecipesItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the Infrastructure.RecipeApi.Client.api.recipes.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Infrastructure.RecipeApi.Client.Api.Recipes.Item.RecipesItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::Infrastructure.RecipeApi.Client.Api.Recipes.Item.RecipesItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("id", position);
                return new global::Infrastructure.RecipeApi.Client.Api.Recipes.Item.RecipesItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Infrastructure.RecipeApi.Client.Api.Recipes.RecipesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RecipesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/recipes", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Infrastructure.RecipeApi.Client.Api.Recipes.RecipesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RecipesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/recipes", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
