basePath: /
definitions:
  recipe.Ingredient:
    properties:
      name:
        type: string
      quantity:
        type: number
      unit:
        type: string
    type: object
  recipe.Recipe:
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a sample server for a recipe app.
  title: Recipe API
  version: "1.0"
paths:
  /recipes:
    post:
      consumes:
      - application/json
      description: Create a new recipe
      parameters:
      - description: Recipe to add
        in: body
        name: recipe
        required: true
        schema:
          $ref: '#/definitions/recipe.Recipe'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/recipe.Recipe'
      summary: Add a new recipe
      tags:
      - recipes
swagger: "2.0"
