// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: mealplanner/v1/mealplanner.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request message for suggesting recipes
type SuggestionsRequest struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	DailyConstraints         []*DailyConstraints    `protobuf:"bytes,1,rep,name=daily_constraints,json=dailyConstraints,proto3" json:"daily_constraints,omitempty"`
	AlreadySelectedRecipeIds []string               `protobuf:"bytes,2,rep,name=already_selected_recipe_ids,json=alreadySelectedRecipeIds,proto3" json:"already_selected_recipe_ids,omitempty"` // UUID strings
	Amount                   int32                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *SuggestionsRequest) Reset() {
	*x = SuggestionsRequest{}
	mi := &file_mealplanner_v1_mealplanner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuggestionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuggestionsRequest) ProtoMessage() {}

func (x *SuggestionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mealplanner_v1_mealplanner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuggestionsRequest.ProtoReflect.Descriptor instead.
func (*SuggestionsRequest) Descriptor() ([]byte, []int) {
	return file_mealplanner_v1_mealplanner_proto_rawDescGZIP(), []int{0}
}

func (x *SuggestionsRequest) GetDailyConstraints() []*DailyConstraints {
	if x != nil {
		return x.DailyConstraints
	}
	return nil
}

func (x *SuggestionsRequest) GetAlreadySelectedRecipeIds() []string {
	if x != nil {
		return x.AlreadySelectedRecipeIds
	}
	return nil
}

func (x *SuggestionsRequest) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

// Response message containing suggested recipe IDs
type SuggestionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecipeIds     []string               `protobuf:"bytes,1,rep,name=recipe_ids,json=recipeIds,proto3" json:"recipe_ids,omitempty"` // UUID strings
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuggestionsResponse) Reset() {
	*x = SuggestionsResponse{}
	mi := &file_mealplanner_v1_mealplanner_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuggestionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuggestionsResponse) ProtoMessage() {}

func (x *SuggestionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mealplanner_v1_mealplanner_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuggestionsResponse.ProtoReflect.Descriptor instead.
func (*SuggestionsResponse) Descriptor() ([]byte, []int) {
	return file_mealplanner_v1_mealplanner_proto_rawDescGZIP(), []int{1}
}

func (x *SuggestionsResponse) GetRecipeIds() []string {
	if x != nil {
		return x.RecipeIds
	}
	return nil
}

// Constraints that apply to a single day
type DailyConstraints struct {
	state                 protoimpl.MessageState  `protogen:"open.v1"`
	IngredientConstraints []*IngredientConstraint `protobuf:"bytes,1,rep,name=ingredient_constraints,json=ingredientConstraints,proto3" json:"ingredient_constraints,omitempty"`
	CuisineConstraints    []*CuisineConstraint    `protobuf:"bytes,2,rep,name=cuisine_constraints,json=cuisineConstraints,proto3" json:"cuisine_constraints,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *DailyConstraints) Reset() {
	*x = DailyConstraints{}
	mi := &file_mealplanner_v1_mealplanner_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DailyConstraints) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailyConstraints) ProtoMessage() {}

func (x *DailyConstraints) ProtoReflect() protoreflect.Message {
	mi := &file_mealplanner_v1_mealplanner_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DailyConstraints.ProtoReflect.Descriptor instead.
func (*DailyConstraints) Descriptor() ([]byte, []int) {
	return file_mealplanner_v1_mealplanner_proto_rawDescGZIP(), []int{2}
}

func (x *DailyConstraints) GetIngredientConstraints() []*IngredientConstraint {
	if x != nil {
		return x.IngredientConstraints
	}
	return nil
}

func (x *DailyConstraints) GetCuisineConstraints() []*CuisineConstraint {
	if x != nil {
		return x.CuisineConstraints
	}
	return nil
}

// Constraint for ingredients
type IngredientConstraint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      string                 `protobuf:"bytes,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"` // UUID string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngredientConstraint) Reset() {
	*x = IngredientConstraint{}
	mi := &file_mealplanner_v1_mealplanner_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngredientConstraint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngredientConstraint) ProtoMessage() {}

func (x *IngredientConstraint) ProtoReflect() protoreflect.Message {
	mi := &file_mealplanner_v1_mealplanner_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngredientConstraint.ProtoReflect.Descriptor instead.
func (*IngredientConstraint) Descriptor() ([]byte, []int) {
	return file_mealplanner_v1_mealplanner_proto_rawDescGZIP(), []int{3}
}

func (x *IngredientConstraint) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

// Constraint for cuisines
type CuisineConstraint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      string                 `protobuf:"bytes,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"` // UUID string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CuisineConstraint) Reset() {
	*x = CuisineConstraint{}
	mi := &file_mealplanner_v1_mealplanner_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CuisineConstraint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CuisineConstraint) ProtoMessage() {}

func (x *CuisineConstraint) ProtoReflect() protoreflect.Message {
	mi := &file_mealplanner_v1_mealplanner_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CuisineConstraint.ProtoReflect.Descriptor instead.
func (*CuisineConstraint) Descriptor() ([]byte, []int) {
	return file_mealplanner_v1_mealplanner_proto_rawDescGZIP(), []int{4}
}

func (x *CuisineConstraint) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

var File_mealplanner_v1_mealplanner_proto protoreflect.FileDescriptor

const file_mealplanner_v1_mealplanner_proto_rawDesc = "" +
	"\n" +
	" mealplanner/v1/mealplanner.proto\x12\x0emealplanner.v1\"\xba\x01\n" +
	"\x12SuggestionsRequest\x12M\n" +
	"\x11daily_constraints\x18\x01 \x03(\v2 .mealplanner.v1.DailyConstraintsR\x10dailyConstraints\x12=\n" +
	"\x1balready_selected_recipe_ids\x18\x02 \x03(\tR\x18alreadySelectedRecipeIds\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x05R\x06amount\"4\n" +
	"\x13SuggestionsResponse\x12\x1d\n" +
	"\n" +
	"recipe_ids\x18\x01 \x03(\tR\trecipeIds\"\xc3\x01\n" +
	"\x10DailyConstraints\x12[\n" +
	"\x16ingredient_constraints\x18\x01 \x03(\v2$.mealplanner.v1.IngredientConstraintR\x15ingredientConstraints\x12R\n" +
	"\x13cuisine_constraints\x18\x02 \x03(\v2!.mealplanner.v1.CuisineConstraintR\x12cuisineConstraints\"3\n" +
	"\x14IngredientConstraint\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\tR\bentityId\"0\n" +
	"\x11CuisineConstraint\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\tR\bentityId2o\n" +
	"\x12MealPlannerService\x12Y\n" +
	"\x0eSuggestRecipes\x12\".mealplanner.v1.SuggestionsRequest\x1a#.mealplanner.v1.SuggestionsResponseB7Z5github.com/platepilot/backend/internal/mealplanner/pbb\x06proto3"

var (
	file_mealplanner_v1_mealplanner_proto_rawDescOnce sync.Once
	file_mealplanner_v1_mealplanner_proto_rawDescData []byte
)

func file_mealplanner_v1_mealplanner_proto_rawDescGZIP() []byte {
	file_mealplanner_v1_mealplanner_proto_rawDescOnce.Do(func() {
		file_mealplanner_v1_mealplanner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mealplanner_v1_mealplanner_proto_rawDesc), len(file_mealplanner_v1_mealplanner_proto_rawDesc)))
	})
	return file_mealplanner_v1_mealplanner_proto_rawDescData
}

var file_mealplanner_v1_mealplanner_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_mealplanner_v1_mealplanner_proto_goTypes = []any{
	(*SuggestionsRequest)(nil),   // 0: mealplanner.v1.SuggestionsRequest
	(*SuggestionsResponse)(nil),  // 1: mealplanner.v1.SuggestionsResponse
	(*DailyConstraints)(nil),     // 2: mealplanner.v1.DailyConstraints
	(*IngredientConstraint)(nil), // 3: mealplanner.v1.IngredientConstraint
	(*CuisineConstraint)(nil),    // 4: mealplanner.v1.CuisineConstraint
}
var file_mealplanner_v1_mealplanner_proto_depIdxs = []int32{
	2, // 0: mealplanner.v1.SuggestionsRequest.daily_constraints:type_name -> mealplanner.v1.DailyConstraints
	3, // 1: mealplanner.v1.DailyConstraints.ingredient_constraints:type_name -> mealplanner.v1.IngredientConstraint
	4, // 2: mealplanner.v1.DailyConstraints.cuisine_constraints:type_name -> mealplanner.v1.CuisineConstraint
	0, // 3: mealplanner.v1.MealPlannerService.SuggestRecipes:input_type -> mealplanner.v1.SuggestionsRequest
	1, // 4: mealplanner.v1.MealPlannerService.SuggestRecipes:output_type -> mealplanner.v1.SuggestionsResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_mealplanner_v1_mealplanner_proto_init() }
func file_mealplanner_v1_mealplanner_proto_init() {
	if File_mealplanner_v1_mealplanner_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mealplanner_v1_mealplanner_proto_rawDesc), len(file_mealplanner_v1_mealplanner_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mealplanner_v1_mealplanner_proto_goTypes,
		DependencyIndexes: file_mealplanner_v1_mealplanner_proto_depIdxs,
		MessageInfos:      file_mealplanner_v1_mealplanner_proto_msgTypes,
	}.Build()
	File_mealplanner_v1_mealplanner_proto = out.File
	file_mealplanner_v1_mealplanner_proto_goTypes = nil
	file_mealplanner_v1_mealplanner_proto_depIdxs = nil
}
