// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mealplanner/v1/mealplanner.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request message for suggesting recipes
type SuggestionsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DailyConstraints          []*DailyConstraints `protobuf:"bytes,1,rep,name=daily_constraints,json=dailyConstraints,proto3" json:"daily_constraints,omitempty"`
	AlreadySelectedRecipeIds  []string            `protobuf:"bytes,2,rep,name=already_selected_recipe_ids,json=alreadySelectedRecipeIds,proto3" json:"already_selected_recipe_ids,omitempty"`
	Amount                    int32               `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *SuggestionsRequest) Reset() {
	*x = SuggestionsRequest{}
}

func (x *SuggestionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuggestionsRequest) ProtoMessage() {}

func (x *SuggestionsRequest) ProtoReflect() protoreflect.Message {
	return nil
}

func (x *SuggestionsRequest) GetDailyConstraints() []*DailyConstraints {
	if x != nil {
		return x.DailyConstraints
	}
	return nil
}

func (x *SuggestionsRequest) GetAlreadySelectedRecipeIds() []string {
	if x != nil {
		return x.AlreadySelectedRecipeIds
	}
	return nil
}

func (x *SuggestionsRequest) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

// Response message containing suggested recipe IDs
type SuggestionsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RecipeIds []string `protobuf:"bytes,1,rep,name=recipe_ids,json=recipeIds,proto3" json:"recipe_ids,omitempty"`
}

func (x *SuggestionsResponse) Reset() {
	*x = SuggestionsResponse{}
}

func (x *SuggestionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuggestionsResponse) ProtoMessage() {}

func (x *SuggestionsResponse) ProtoReflect() protoreflect.Message {
	return nil
}

func (x *SuggestionsResponse) GetRecipeIds() []string {
	if x != nil {
		return x.RecipeIds
	}
	return nil
}

// Constraints that apply to a single day
type DailyConstraints struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IngredientConstraints []*IngredientConstraint `protobuf:"bytes,1,rep,name=ingredient_constraints,json=ingredientConstraints,proto3" json:"ingredient_constraints,omitempty"`
	CuisineConstraints    []*CuisineConstraint    `protobuf:"bytes,2,rep,name=cuisine_constraints,json=cuisineConstraints,proto3" json:"cuisine_constraints,omitempty"`
}

func (x *DailyConstraints) Reset() {
	*x = DailyConstraints{}
}

func (x *DailyConstraints) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailyConstraints) ProtoMessage() {}

func (x *DailyConstraints) ProtoReflect() protoreflect.Message {
	return nil
}

func (x *DailyConstraints) GetIngredientConstraints() []*IngredientConstraint {
	if x != nil {
		return x.IngredientConstraints
	}
	return nil
}

func (x *DailyConstraints) GetCuisineConstraints() []*CuisineConstraint {
	if x != nil {
		return x.CuisineConstraints
	}
	return nil
}

// Constraint for ingredients
type IngredientConstraint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EntityId string `protobuf:"bytes,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
}

func (x *IngredientConstraint) Reset() {
	*x = IngredientConstraint{}
}

func (x *IngredientConstraint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngredientConstraint) ProtoMessage() {}

func (x *IngredientConstraint) ProtoReflect() protoreflect.Message {
	return nil
}

func (x *IngredientConstraint) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

// Constraint for cuisines
type CuisineConstraint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EntityId string `protobuf:"bytes,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
}

func (x *CuisineConstraint) Reset() {
	*x = CuisineConstraint{}
}

func (x *CuisineConstraint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CuisineConstraint) ProtoMessage() {}

func (x *CuisineConstraint) ProtoReflect() protoreflect.Message {
	return nil
}

func (x *CuisineConstraint) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

var File_mealplanner_v1_mealplanner_proto protoreflect.FileDescriptor

var _ protoreflect.FileDescriptor = File_mealplanner_v1_mealplanner_proto

func init() {
}

var _ sync.Locker
var _ reflect.Kind
