// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// MealPlannerServiceClient is the client API for MealPlannerService service.
type MealPlannerServiceClient interface {
	SuggestRecipes(ctx context.Context, in *SuggestionsRequest, opts ...grpc.CallOption) (*SuggestionsResponse, error)
}

type mealPlannerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMealPlannerServiceClient(cc grpc.ClientConnInterface) MealPlannerServiceClient {
	return &mealPlannerServiceClient{cc}
}

func (c *mealPlannerServiceClient) SuggestRecipes(ctx context.Context, in *SuggestionsRequest, opts ...grpc.CallOption) (*SuggestionsResponse, error) {
	out := new(SuggestionsResponse)
	err := c.cc.Invoke(ctx, "/mealplanner.v1.MealPlannerService/SuggestRecipes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MealPlannerServiceServer is the server API for MealPlannerService service.
type MealPlannerServiceServer interface {
	SuggestRecipes(context.Context, *SuggestionsRequest) (*SuggestionsResponse, error)
	mustEmbedUnimplementedMealPlannerServiceServer()
}

// UnimplementedMealPlannerServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMealPlannerServiceServer struct {
}

func (UnimplementedMealPlannerServiceServer) SuggestRecipes(context.Context, *SuggestionsRequest) (*SuggestionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SuggestRecipes not implemented")
}

func (UnimplementedMealPlannerServiceServer) mustEmbedUnimplementedMealPlannerServiceServer() {}

// UnsafeMealPlannerServiceServer may be embedded to opt out of forward compatibility for this service.
type UnsafeMealPlannerServiceServer interface {
	mustEmbedUnimplementedMealPlannerServiceServer()
}

func RegisterMealPlannerServiceServer(s grpc.ServiceRegistrar, srv MealPlannerServiceServer) {
	s.RegisterService(&MealPlannerService_ServiceDesc, srv)
}

var MealPlannerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mealplanner.v1.MealPlannerService",
	HandlerType: (*MealPlannerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SuggestRecipes",
			Handler:    _MealPlannerService_SuggestRecipes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mealplanner/v1/mealplanner.proto",
}

func _MealPlannerService_SuggestRecipes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SuggestionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MealPlannerServiceServer).SuggestRecipes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mealplanner.v1.MealPlannerService/SuggestRecipes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MealPlannerServiceServer).SuggestRecipes(ctx, req.(*SuggestionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}
