run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unparam
    - gosec
    - prealloc

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    enable-all: true
    disable:
      - fieldalignment # Too strict for most cases

  gofmt:
    simplify: true

  goimports:
    local-prefixes: github.com/platepilot/backend

  misspell:
    locale: US

  gosec:
    excludes:
      - G104 # Audit errors not checked - too noisy

  prealloc:
    simple: true
    range-loops: true
    for-loops: false

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

  exclude-rules:
    # Exclude some linters from running on test files
    - path: _test\.go
      linters:
        - gosec
        - unparam

    # Exclude generated protobuf files
    - path: \.pb\.go$
      linters:
        - all

output:
  formats:
    - format: colored-line-number
  sort-results: true
