// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Infrastructure.MealPlannerApi.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SuggestionsRequest : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The alreadySelectedRecipeIds property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<Guid?>? AlreadySelectedRecipeIds { get; set; }
#nullable restore
#else
        public List<Guid?> AlreadySelectedRecipeIds { get; set; }
#endif
        /// <summary>The amount property</summary>
        public int? Amount { get; set; }
        /// <summary>The constraints property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Infrastructure.MealPlannerApi.Client.Models.SuggestionConstraintsRequest? Constraints { get; set; }
#nullable restore
#else
        public global::Infrastructure.MealPlannerApi.Client.Models.SuggestionConstraintsRequest Constraints { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Infrastructure.MealPlannerApi.Client.Models.SuggestionsRequest"/> and sets the default values.
        /// </summary>
        public SuggestionsRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Infrastructure.MealPlannerApi.Client.Models.SuggestionsRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Infrastructure.MealPlannerApi.Client.Models.SuggestionsRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Infrastructure.MealPlannerApi.Client.Models.SuggestionsRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "alreadySelectedRecipeIds", n => { AlreadySelectedRecipeIds = n.GetCollectionOfPrimitiveValues<Guid?>()?.AsList(); } },
                { "amount", n => { Amount = n.GetIntValue(); } },
                { "constraints", n => { Constraints = n.GetObjectValue<global::Infrastructure.MealPlannerApi.Client.Models.SuggestionConstraintsRequest>(global::Infrastructure.MealPlannerApi.Client.Models.SuggestionConstraintsRequest.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfPrimitiveValues<Guid?>("alreadySelectedRecipeIds", AlreadySelectedRecipeIds);
            writer.WriteIntValue("amount", Amount);
            writer.WriteObjectValue<global::Infrastructure.MealPlannerApi.Client.Models.SuggestionConstraintsRequest>("constraints", Constraints);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
